name: Dependency Updates

on:
  schedule:
    # Run weekly on Mondays at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Install npm-check-updates
      run: npm install -g npm-check-updates

    - name: Check for updates
      id: check-updates
      run: |
        # Check for updates and save output
        ncu --jsonUpgraded > updates.json
        
        # Check if there are updates
        if [ -s updates.json ] && [ "$(cat updates.json)" != "{}" ]; then
          echo "has-updates=true" >> $GITHUB_OUTPUT
          echo "Updates available:"
          cat updates.json
        else
          echo "has-updates=false" >> $GITHUB_OUTPUT
          echo "No updates available"
        fi

    - name: Update dependencies
      if: steps.check-updates.outputs.has-updates == 'true'
      run: |
        # Update dependencies
        ncu -u
        npm install

    - name: Run tests
      if: steps.check-updates.outputs.has-updates == 'true'
      run: |
        npm run ci

    - name: Create Pull Request
      if: steps.check-updates.outputs.has-updates == 'true'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore(deps): update dependencies'
        title: 'chore(deps): automated dependency updates'
        body: |
          ## Automated Dependency Updates
          
          This PR contains automated dependency updates generated by the weekly dependency update workflow.
          
          ### Changes
          - Dependencies have been updated to their latest compatible versions
          - All tests have passed
          
          ### Review Notes
          - Please review the changes carefully
          - Check the changelog/release notes for any breaking changes
          - Ensure all functionality works as expected
          
          Auto-generated by GitHub Actions 🤖
        branch: automated-dependency-updates
        delete-branch: true
        draft: false